# Parameter file
# test:
  # General Params 
  enable_voxl_offset: true # True if only using VIO/HereFlow (i.e no external heading sources)
  takeoff_height:     1.50  # Auto-Takeoff height [in m]

  # Waypoint Execution Behaviour
  yaw_hold:       true # Enable to make the drone face the intial heading at all times, False to face towards next WP
  speed_hor_max:  2.0 # Maximum horizontal speed limit [in m/s] (Manual and Auto modes)
  speed_vert_max: 2.0 # Maximum vertical speed limit [in m/s] (Manual and Auto modes)
  wp_radius:      0.25 # Waypoint radius tolerance [in m]
  wp_mode:        1 # Set to '0' for reading WPs from file (from ../misc/waypoints.txt), '1' for Generating Grid WPs (from ../misc/rack_info.json)
  exec_mode:      1 # Set to '0' for Pose only setpoints, '1' for Pose-Vel setpoints (smoother)
  waypoint_hold_time: 0.0 # Hold time in seconds to make the MAV briefly hold at current WP before moving-on
  vel_ctrl_gain: 3.50 # Proportional gain for velocity FF controller
  wps_file_dir: "../misc/waypoints.txt" # File containing the pre-defined WP definitions
  rack_info_dir: "../misc/rack_info.json" # File containing information of the virtual rack
  heading_offset_deg: 0.0 # Yaw offset for scanning
  read_extern_yaw: True # Use yaw setpoints from file
  align_yaw_before_move: True # Align yaw before starting translation
  
  # Grid Planner 
  enable_rack_facing: false # Set to true to make the drone face the rack
  grid_scan_mode: 'HOR' # Grid planning mode
  num_grid_levels: 5  # Number of scanning levels (hor/vert respectively)

  # PX4 parameter value checklist
  # Set all param values to be checked here. Mission won't start unless all param checks pass
  enable_px4_param_checks: False
  px4_param_checklist: {
    'EKF2_AID_MASK' :  2
  }
